### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andreolf**
Capitalized ConsenSys

### CODE REVIEW

**Review by EmanHerawy — APPROVED** [review]
Hi @andreolf, 
Thanks for your contributions. Much appreciated.

**Comment by andreolf** [comment]
pleasure man!

what do you want to do with the colors? i see they are not showing up well

________________________________

**Comment by EmanHerawy** [comment]
I'm trying to fix them. I don't know why it's not working on github while it it works very well when checking locally 
image

**Comment by andreolf** [comment]
might be better to just use those emoji that are readme recognized 🟡 🟢 🛑
________________________________

**Pull request merged**
